// Mocks generated by Mockito 5.1.0 from annotations
// in project/test/building_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project/server/server.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Server].
///
/// See the documentation for Mockito's code generation for more information.
class MockServer extends _i1.Mock implements _i2.Server {
  MockServer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> createAccount(
          Map<String, dynamic>? accountInfo) =>
      (super.noSuchMethod(Invocation.method(#createAccount, [accountInfo]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> login(Map<String, dynamic>? loginInfo) =>
      (super.noSuchMethod(Invocation.method(#login, [loginInfo]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> getBuildingDetails(String? building) =>
      (super.noSuchMethod(Invocation.method(#getBuildingDetails, [building]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> getRoomDetails(Map<String, dynamic>? room) =>
      (super.noSuchMethod(Invocation.method(#getRoomDetails, [room]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> getRoomBookings(
          Map<String, dynamic>? room) =>
      (super.noSuchMethod(Invocation.method(#getRoomBookings, [room]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> getUserInfo(String? userEmail) =>
      (super.noSuchMethod(Invocation.method(#getUserInfo, [userEmail]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> getUserBookings(String? userEmail) =>
      (super.noSuchMethod(Invocation.method(#getUserBookings, [userEmail]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> book(Map<String, dynamic>? bookingDetails) =>
      (super.noSuchMethod(Invocation.method(#book, [bookingDetails]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> amendBooking(
          Map<String, dynamic>? bookingDetails) =>
      (super.noSuchMethod(Invocation.method(#amendBooking, [bookingDetails]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<void> cancelBooking(Map<String, dynamic>? bookingDetails) =>
      (super.noSuchMethod(Invocation.method(#cancelBooking, [bookingDetails]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteFromHistory(Map<String, dynamic>? bookingDetails) =>
      (super.noSuchMethod(
          Invocation.method(#deleteFromHistory, [bookingDetails]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String localhost() =>
      (super.noSuchMethod(Invocation.method(#localhost, []), returnValue: '')
          as String);
}
